# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='title',
        ),
    ]
